---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: '{{ source_url }}?rev={{ revision }}'
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: stgrh01cr-app-wjqaa
    appstudio.openshift.io/component: stgrh01cr-app-wjqaa-comp-0
    pipelines.appstudio.openshift.io/type: build
  name: stgrh01cr-app-wjqaa-comp-0-on-pull-request
  namespace: konflux-perfscale-4-tenant
spec:
  params:
    - name: package-name
      value: libecpg
    - name: git-url
      value: "{{ source_url }}"
    - name: revision
      value: "{{ revision }}"
    - name: target-branch
      value: "{{ target_branch }}"
    - name: ociStorage
      value: "quay.io/redhat-user-workloads/$(context.taskRun.namespace)/stgrh01cr-app-wjqaa-comp-0:on-pr-{{revision}}"
    - name: build-platforms
      value:
        - localhost
        - linux/amd64
        - linux/arm64
    - name: build-architectures
      value:
        - aarch64
        - x86_64
    - name: strictArch
      value: "false"
    - name: self-ref-url
      value: "https://github.com/konflux-ci/rpmbuild-pipeline.git"
    - name: self-ref-revision
      value: 47149d31753c0bf46cc9fe5dc50af3716aeea63c
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: https://github.com/konflux-ci/rpmbuild-pipeline.git
      - name: revision
        value: "main"
      - name: pathInRepo
        value: pipeline/build-rpm-package.yaml
  taskRunTemplate:
    serviceAccountName: build-pipeline-stgrh01cr-app-wjqaa-comp-0
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
